# Generated by Django 6.0.5 on 2026-09-16 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GardeMoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('groupe', models.CharField(blank=True, max_length=100, null=True)),
                ('montant_total', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('montant_groupe', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('montant_em', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('montant_caritas', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('montant_jeunesse', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('montant_paroisse', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
