# Generated by Django 6.0.5 on 2026-05-27 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('cure', 'Curé'), ('secretaire', 'Secrétaire'), ('vicaire', 'Vicaire')], max_length=20),
        ),
    ]
