# Generated by Django 6.0.2 on 2026-03-21 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='horairemesse',
            name='actif',
        ),
        migrations.AddField(
            model_name='horairemesse',
            name='fete',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='horairemesse',
            name='type',
            field=models.CharField(choices=[('normal', 'Normal'), ('special', 'Spécial')], default='normal', max_length=10),
        ),
    ]
