# Generated by Django 6.0.2 on 2026-03-20 15:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('messes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Demandeur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('telephone', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Intention',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intention', models.TextField()),
                ('nombre_messes', models.PositiveIntegerField(default=1)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('validee', 'Validée'), ('refusee', 'Refusée')], default='en_attente', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('demandeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='intentions.demandeur')),
            ],
        ),
        migrations.CreateModel(
            name='IntentionMesse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('est_lue', models.BooleanField(default=False)),
                ('intention', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='intentions.intention')),
                ('messe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='messes.messe')),
            ],
            options={
                'unique_together': {('intention', 'messe')},
            },
        ),
    ]
