# Generated by Django 6.0.2 on 2026-03-21 09:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intentions', '0001_initial'),
        ('messes', '0002_remove_horairemesse_actif_horairemesse_fete_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='intention',
            old_name='nombre_messes',
            new_name='nombre',
        ),
        migrations.RemoveField(
            model_name='intention',
            name='statut',
        ),
        migrations.AddField(
            model_name='intention',
            name='horaire',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='messes.horairemesse'),
        ),
        migrations.DeleteModel(
            name='IntentionMesse',
        ),
    ]
