# Generated by Django 6.0.1 on 2026-05-21 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intentions', '0003_intention_montant'),
    ]

    operations = [
        migrations.AddField(
            model_name='intention',
            name='categorie',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
