# Generated by Django 6.0.5 on 2026-05-27 16:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intentions', '0004_intention_categorie'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MesseSpeciale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categorie', models.CharField(blank=True, choices=[('Action de grâce', 'Action de grâce'), ('Obsèques', 'Obsèques'), ('Mariage', 'Mariage'), ('Baptême bébé', 'Baptême bébé')], max_length=100, null=True)),
                ('date_evenement', models.DateField()),
                ('montant', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('role_enregistreur', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('demandeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='intentions.demandeur')),
                ('enregistre_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messes_enregistrees', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
