# Generated by Django 6.0.5 on 2026-05-27 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intentions', '0005_messespeciale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messespeciale',
            name='categorie',
            field=models.CharField(blank=True, choices=[('Action de grâce', 'Action de grâce'), ('Obsèques', 'Obsèques'), ('Mariage', 'Mariage'), ('Diplôme', 'Diplôme'), ('Baptême bébé', 'Baptême bébé')], max_length=100, null=True),
        ),
    ]
