# Generated by Django 6.0.5 on 2026-05-27 17:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intentions', '0006_alter_messespeciale_categorie'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='intention',
            name='enregistre_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='intentions_enregistrees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='intention',
            name='role_enregistreur',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
