# Generated by Django 6.0.5 on 2026-05-27 18:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intentions', '0007_intention_enregistre_par_intention_role_enregistreur'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AutreFrais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categorie', models.CharField(blank=True, choices=[('Denier de culte', 'Denier de culte'), ('Dîme', 'Dîme'), ('Don', 'Don'), ('Caméra', 'Caméra'), ('Photo', 'Photo')], max_length=100, null=True)),
                ('date_evenement', models.DateField(blank=True, null=True)),
                ('montant', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('role_enregistreur', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('demandeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='intentions.demandeur')),
                ('enregistre_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='autres_frais_enregistres', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
