# Generated by Django 6.0.5 on 2026-05-29 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intentions', '0008_autrefrais'),
    ]

    operations = [
        migrations.AddField(
            model_name='intention',
            name='statut',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
