# Generated by Django 6.0.5 on 2026-05-29 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intentions', '0009_intention_statut'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intention',
            name='statut',
            field=models.CharField(default='en_attente', max_length=20),
            preserve_default=False,
        ),
    ]
