# Generated by Django 6.0.5 on 2026-07-29 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intentions', '0010_alter_intention_statut'),
    ]

    operations = [
        migrations.AddField(
            model_name='intention',
            name='checkout_id',
            field=models.CharField(blank=True, max_length=150, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='intention',
            name='date_paiement',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='intention',
            name='statut_paiement',
            field=models.CharField(default='en_attente', max_length=20),
        ),
        migrations.AddField(
            model_name='intention',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
