# Generated by Django 6.0.5 on 2026-09-16 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intentions', '0011_intention_checkout_id_intention_date_paiement_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autrefrais',
            name='categorie',
            field=models.CharField(blank=True, choices=[('Denier de culte', 'Denier de culte'), ('Dîme', 'Dîme'), ('Don simple', 'Don simple'), ('Don hostie & vin', 'Don hostie & vin'), ('Caméra', 'Caméra'), ('Photo', 'Photo')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='demandeur',
            name='nom',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='messespeciale',
            name='categorie',
            field=models.CharField(blank=True, choices=[('Action de grâce', 'Action de grâce'), ('Obsèques', 'Obsèques'), ('Mariage', 'Mariage'), ('Diplôme', 'Diplôme'), ('Baptême bébé', 'Baptême bébé'), ('Baptême adulte', 'Baptême adulte')], max_length=100, null=True),
        ),
    ]
